# Generated by Django 5.2.6 on 2025-11-27 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_interval", models.IntegerField(default=1)),
                ("second_interval", models.IntegerField(default=6)),
                ("interval_multiplier", models.FloatField(default=1.0)),
                ("max_interval", models.IntegerField(default=365)),
                ("min_easiness", models.FloatField(default=1.3)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="vocab.telegramuser",
                    ),
                ),
            ],
        ),
    ]
