# Generated by Django 5.2.6 on 2025-11-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0002_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="voice_gender",
            field=models.CharField(
                choices=[("female", "Женский"), ("male", "Мужской")],
                default="female",
                max_length=10,
            ),
        ),
    ]
