# Generated by Django 5.2.6 on 2025-12-02 16:25

import vocab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_somemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vocab.models.card_image_upload_path),
        ),
    ]
