# Generated by Django 5.2.6 on 2026-01-25 10:01

import django.db.models.deletion
import django.utils.timezone
import words.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vocab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("translation", models.CharField(max_length=255)),
                (
                    "source_lang",
                    models.CharField(
                        default="en",
                        help_text="Language of the original word (en/ru)",
                        max_length=10,
                    ),
                ),
                (
                    "next_review",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("interval", models.IntegerField(default=1)),
                ("repetitions", models.IntegerField(default=0)),
                ("ease_factor", models.FloatField(default=2.5)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=words.models.word_image_upload_path,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="vocab.telegramuser",
                    ),
                ),
            ],
        ),
    ]
