# Generated by Django 5.2.6 on 2025-11-29 18:49

import django.db.models.deletion
import words.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0004_somemodel"),
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=words.models.word_image_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words",
                to="vocab.telegramuser",
            ),
        ),
    ]
