# Generated by Django 5.2.4 on 2025-09-08 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_word'),
        ('words', '0002_alter_word_next_review_alter_word_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_words', to='vocab.telegramuser'),
        ),
    ]
